### ISSUE TITLE
manual to setup on wamp or hostgator server

### ISSUE THREAD

**Issue by vinogans** [haleymt/large#1]
how can i install this on hostgator server or wamp on windows to test it ... I cant find any configuration please help

**Comment by haleymt** [comment]
If you simply want to test the site's functionality, I suggest you either view it at the [live link](medium-large.herokuapp.com) or clone it to your machine and host it at the standard rails server (WEBrick). I'm afraid I can't help you with installing on those specific servers.

**Comment by vinogans** [comment]
thats what all I needed the platform that I can use ur design in it .. you should add this to the manual I mean referring to WEBrick
