### ISSUE TITLE
after running it on a local server

### ISSUE THREAD

**Issue by vinogans** [haleymt/large#2]
when i run ur app on a local server it worked well except when i register it say" We're sorry, but something went wrong."

If you are the application owner check the logs for more information. 

and when i press take a tour .. it say same thing .. is there any thing i must re-config it ?

**Comment by vinogans** [comment]
never mind I solved it by this commands rake db:seed  then   rake db:migrate .....i also edit database.yml with database name and user name ... it works now but it dont display post`s in main page just in the profile of the user ... beside is there an admin account I can create to control all post`s

**Comment by haleymt** [comment]
Hi, I'm afraid these are all basic rails questions and not actual bugs in the program, so I suggest you head to google or stackoverflow.com with your questions in the future! The database I used is postgresql, and you will either need to configure that or use a different database. If you would like to create an admin user you will have to do it yourself. Posts will not appear on the main page unless you are following the users/publications that post them.

**Comment by vinogans** [comment]
I am sorry for my limited knowledge but thanks for the info :+1:  i know what i wrote is not an issue`s ... but i didnt know how to contact with the developer except with this ....  is there any option to create an admin user in this or i have to write a code to make it happen ... I am sorry again ...  and thanks for replying

**Comment by haleymt** [comment]
No worries, I know how it is when starting out! If you want to create an admin user, you'll have to code that yourself, unfortunately. I'm sure there's great advice floating around on the web for how to do that in a rails project, though.

**Comment by vinogans** [comment]
thanks :+1:
